# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
                ('placar_time1', models.IntegerField()),
                ('placar_time2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='time1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='bolao.Time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='bolao.Time'),
        ),
    ]
