# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_auto_20170926_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('placa_1', models.IntegerField()),
                ('placa_2', models.IntegerField()),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.Partida')),
            ],
        ),
    ]
